line_length:
  warning: 150
  error: 300
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  ignores_function_declarations: true

identifier_name:
     allowed_symbols: "_"
